language: java
jdk: oraclejdk8

addons:
  sonarcloud:
    organization: "coder-chenzhi-github"


script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - >
      mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install \
        sonar:sonar -Dsonar.projectKey=coder-chenzhi_spring-petclinic \
                    -Dsonar.organization=coder-chenzhi-github \
                    -Dsonar.host.url=https://sonarcloud.io \
                    -Dsonar.login=$SONAR_TOKEN

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
